### ISSUE TITLE
What is the copyright position on map layers created from vectorising reproductions of out of copyright maps

### ISSUE THREAD

**Issue by Addaci** [Maphackathon/data-sets#31]
For example, Ian Rawes has scanned and stitched together individual sheets of Thomas Milne's land use maps (1800) and map tiled them. He has used modern physical reproductions of out of copyright maps. If we vectorise his digital reproductions and thus create new layers, to which we may further manipulate and modify, are these clearly derivative works, and what is the copyright position on these possibly derivative works. Ian's digital copy was probably made from a physical copy of the London Topographical Society's physical reproduction. https://catalyst.library.jhu.edu/catalog/bib_2028331; http://www.londontopsoc.org/regency1

**British Library**

See: The British Library has one sheet georeferenced and digitised, showing the west and south-west of the city. Shelfmark: Shelfmark: Maps.Crace XIX; Item no.: 28; Length: 432; Width: 508; Scale: Muillimetres; Genre: Map; Map scale description: No scale given. http://britishlibrary.georeferencer.com/map/HuTnS43MpEwwC2Og1FI9bc/201311061938-ylmNan/visualize

It is described as "MILNE'S PLAN of the CITIES of LONDON and WESTMINSTER, circumjacent TOWNS and PARISHES &c. laid down from a TRIGONOMETRICAL SURVEY taken in the YEARS 1795-1799". Attached metadata notes state "This is one of six sheets forming Milne's map of the area twenty miles around London. It was the first to make use of the 'Trygonometrical Survey' founded in 1791.

This sheet covers the area to the west and south-west of the capital. It shows all the field boundaries and indicates land use with a complex system of letters and colours. The key is featured on the top corners. The borders of the map are divided in minutes and seconds, giving scale, angles of observations and magnetic variations. Thomas Milne trained as an estate surveyor and worked on the first Ordnance Survey map of Kent."

**London Sound Survey**

See South East sheet: http://www.soundsurvey.org.uk/index.php/survey/historical_london_map/milne_1800/2147/

**Royal Collections/Royal Museum Greenwich**

The Royal Collections has a digitisation of a C20th reproduction of Thomas Milne's Land Use Map of London and Environs in 1800.  after drawing of 1800, Introduction by G.B.C.Bull on 5 pages. 6 illustrations and maps (numbered in parts). Inclosed in brown folder. Original in British Library. RCIN 702193. This reproduces text and six colour map images. The digital images assert "Royal Collection Trust/© Her Majesty Queen Elizabeth II 2017": https://www.royalcollection.org.uk/collection/702193/thomas-milnes-land-use-map-of-london-and-environs-in-1800

**Comment by mpdavies** [comment]
We have always cautiously worked on the basis that the copyright in the unwarped original digital image of a map lies with the owner  - assuming they in turn have the right to distribute the image of an original map (eg because they own it). The British Library for instance claims copyright in all images of its own  maps, manuscripts etc. and will normally charge accordingly for reproducing them. They supplied us the individual Morgan sheets on the condition that we did not make them available. However, we are allowed to make the stitched-together and georeferenced version available via our licence agreement with BL. The same applies to Motco who supplied the Rocque sheets for Locating London's Past. The vector data derived from both maps is nothing to do with them and belongs to us (ie University of London for Morgan, and the Locating London's Past team of UoL, Sheffield and Hertfordshire for Rocque). I think the view is that derivative layers are the equivalent of transcriptions of documents, or data extracted from them - ie that copyright holders of the originals have no claim over them. 
Sometimes, as with the British Museum, a copyright holder can decide to release images on a CC-type licence, for non-commercial use - or even for publication in a book. If that is the case then a digital surrogate could presumably be made available under the same terms.
Digital images of published works such as London Top Soc might technically be awkward from a copyright point of view, unless the copyright in the published work itself has expired - doesn't matter if the orginal map itself is hundreds of years old. A warped version of an in-copyright LTS map is the grey area - as I say, we specifically made sure that BL and Motco were ok, even though in both cases we altered the map sheets significantly by stitching together and warping. So if I were using an LTS map from a publication that is in copyright I would definitely talk to them about it.

**Comment by Addaci** [comment]
Very useful Matthew. My conclusion is that we can definitely use out of copyright maps and plans which have been imaged, even if the digitiser of that out of copyright object claims copyright over the digital image, providing we don't want to republish the image, but instead wish to create a layer based on abstracting and modifying certain features from the digital image and publishing that new layer ourselves as an independent object. It may of course be both polite and good sense to approach the party who claims the digital copyright before we publish our independent layer.

In the case of the Thomas Milne landuse map I would clike to create a vectorised layer which sets out the field boundaries. Following your logic this should be possible - the British Library owns the orginal map (CRACE IX) and must have given the London Topographical Society permission to photograph and reproduce as photgraphic plates in their publication.  This publication is still available at the LTS, described as "Thomas Milne’s Land Use Map of London and Environs with introductory notes by Dr G B G Bull. Milne's map of 1800 provides a detailed colour-coded picture of land use, identifying arable, market gardens, meadows and pastures. Six colour sheets plus three sheets of introduction, in folder. Publication no 118/9 (1975/6). £20." http://www.londontopsoc.org/regency1. The LTS version is dated 1975.

Do you have a contact at the London Topographical Society?

**Comment by mpdavies** [comment]
Yes, I think that follows - though am obviously not a lawyer! I guess option 1 would be to talk to the BL direct, not least as you might get a better quality image (have all the Crace images been digitised?). After that you might as well initially contact Roger Cline, whose email is on the LTS page you linked to. They might in any case refer you to the BL!
